# Generated by Django 4.2.6 on 2023-11-04 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_pictures_alter_place_description_long_delete_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place', verbose_name='Принадлежность локации'),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(unique=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(unique=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Заголовок'),
        ),
    ]
