# Generated by Django 4.2.6 on 2023-11-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_picture_alter_place_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(default='default image', unique=True, upload_to='', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
